version: '2'
services:
  postgres:
    image: postgres
    environment:
      PSQL_DB: ${PSQL_DB}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - '${PSQL_PORT}:${PSQL_PORT}'

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      PSQL_HOST: ${PSQL_HOST}
