version: '2'
services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '${PSQL_PORT}:${PSQL_PORT}'

  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    env_file:
      - .env
