version: '3'
services:
  postgres:
    image: postgres
    environment:
      PSQL_DB: ${PSQL_DB}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PSQL_HOST: ${PSQL_HOST}
